def newBuildDir = rootProject.layout.buildDirectory

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.layout.buildDirectory = newBuildDir
subprojects {
    project.layout.buildDirectory = newBuildDir.dir(project.name)
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete newBuildDir
}
